// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BarChart: typeof import('./src/components/Charts/BarChart.vue')['default']
    Date: typeof import('./src/components/Date/index.vue')['default']
    Empty: typeof import('./src/components/Empty/index.vue')['default']
    GaugeChart: typeof import('./src/components/Charts/GaugeChart.vue')['default']
    LineChart: typeof import('./src/components/Charts/LineChart.vue')['default']
    LiquidChart: typeof import('./src/components/Charts/LiquidChart.vue')['default']
    Number: typeof import('./src/components/Number/index.vue')['default']
    PieChart: typeof import('./src/components/Charts/PieChart.vue')['default']
    RadarChart: typeof import('./src/components/Charts/RadarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeChart: typeof import('./src/components/Charts/TreeChart.vue')['default']
    WordChart: typeof import('./src/components/Charts/WordChart.vue')['default']
  }
}
